title: "Dr. Semuhi Sinanoglu"
author: "Dr. Semuhi Sinanoglu"
description: <a href="https://www.idos-research.de/en/research-staff/sinanoglu-semuhi/"> German Institute of Development and Sustainability (IDOS) </a>
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "research.md", title: "Research"}
  - {file: "teaching.md", title: "Teaching"}
  - {file: "other-pub.md", title: "Other Publications"}
  # - {file: "resume.md", title: "Resume"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:Semuhi.Sinanoglu@idos-research.de"}
  - {title: Github, icon: github, url: "https://github.com/semuhi"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/semuhisinanoglu/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/semuhi"}
  - {title: Google Scholar, icon: google-plus, url: "https://scholar.google.com/citations?user=4IlRWR0AAAAJ&hl=tr"}
  - {title: Bluesky, icon: bluesky, url: "https://bsky.app/profile/semuhi.bsky.social"}

  - {title: Researchgate, icon: researchgate, url: "https://www.researchgate.net/profile/Semuhi-Sinanoglu-2"}
  

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
