#!/usr/bin/env ruby
# Generates one page per long-form publication.
#
# Reads  : _data/publications.yml
# Writes : _data/pubpages.yml   (id -> slug map, read by the wall, the map, and
#                                the portfolio rows so their links stay in sync)
#          work/<slug>.md       (one stub per item; the body renders from
#                                _data via _includes/c-pub-page.html)
#
# Rule: an item gets a page when its type is in PAGE_TYPES and it has an
# `abstract`. Every other item keeps its row and links straight to the
# publisher.
#
# Run after you add or edit a publication:
#   ruby tools/gen-pub-pages.rb
#
# The stubs carry `generated: tools/gen-pub-pages.rb`. The script deletes any
# stub with that marker that no longer has a matching item, so a removed or
# renamed item does not leave a dead page behind.
require "yaml"
require "json"
require "fileutils"

ROOT   = File.expand_path("..", __dir__)
PUBS   = File.join(ROOT, "_data", "publications.yml")
MAP    = File.join(ROOT, "_data", "pubpages.yml")
OUTDIR = File.join(ROOT, "work")
MARKER = "tools/gen-pub-pages.rb"

# Types that get their own page (user decision 2026-08-24). These are the
# long-form outputs a reader can cite. An op-ed is short and lives at the
# publisher; a file-drawer item is an unpublished result. Both stay wall-only.
PAGE_TYPES = %w[
  academic-peer-review
  academic-working-paper
  academic-discussion-paper
  academic-chapter
  academic-thesis
  policy-brief
  report
  essay
].freeze

# ASCII fold for the few non-ASCII characters the titles use.
FOLD = {
  "ı" => "i", "İ" => "i", "ğ" => "g", "Ğ" => "g", "ş" => "s", "Ş" => "s",
  "ö" => "o", "Ö" => "o", "ü" => "u", "Ü" => "u", "ç" => "c", "Ç" => "c",
  "é" => "e", "è" => "e", "á" => "a", "í" => "i", "ó" => "o", "ú" => "u",
  "’" => "", "‘" => "", "“" => "", "”" => "", "–" => "-", "—" => "-"
}.freeze

# Words that read as noise at the end of a cut slug.
TAIL = %w[a an and as at by during for from in into is of on or the to under with].freeze

def slugify(text, max = 60)
  s = text.dup
  FOLD.each { |from, to| s.gsub!(from, to) }
  s = s.downcase.gsub(/['’‘]/, "").gsub(/[^a-z0-9]+/, "-").gsub(/\A-+|-+\z/, "")
  if s.length > max
    cut = s[0, max]
    cut = cut[0, cut.rindex("-")] if cut.include?("-")
    s = cut
  end
  parts = s.split("-")
  parts.pop while parts.size > 3 && TAIL.include?(parts.last)
  parts.join("-")
end

# The head of a two-part academic title ("Main claim: the long subtitle") is
# the memorable half, so it makes the better URL. Keep the full title when the
# head is too short to identify the item.
def slug_source(item)
  return item["title_short"] if item["title_short"]
  head = item["title"].split(/[:?]/).first.to_s.strip
  head.length >= 20 ? head : item["title"]
end

# One sentence of plain metadata plus the blurb. Meta descriptions are the
# first thing a retrieval pipeline reads, so name the person and the venue.
def description(item, type_label)
  bits = [item["blurb"].to_s.strip]
  cite = "#{type_label}"
  cite += ", #{item["venue"]}" if item["venue"] && !item["venue"].empty? &&
                                  item["venue"].downcase != type_label.downcase
  cite += " (#{item["year"]}), by Semuhi Sinanoglu"
  cite += " with #{item["coauthors_full"] || item["coauthors"]}" if item["coauthors"]
  bits << "#{cite}."
  d = bits.reject(&:empty?).join(" ").gsub(/\s+/, " ")
  return d if d.length <= 250
  cut = d[0, 250]
  "#{cut[0, cut.rindex(" ")]}..."
end

items  = YAML.load_file(PUBS)
labels = YAML.load_file(File.join(ROOT, "_data", "portfolios.yml"))["type_labels"]
pageable = items.select do |i|
  PAGE_TYPES.include?(i["type"]) &&
    i["abstract"] && !i["abstract"].to_s.strip.empty?
end

seen = {}
rows = pageable.map do |i|
  base = slugify(slug_source(i))
  slug = base
  slug = "#{base}-#{i["id"]}" if seen.key?(slug)
  raise "slug clash: #{slug}" if seen.key?(slug)
  seen[slug] = i["id"]
  { "id" => i["id"], "slug" => slug }
end

FileUtils.mkdir_p(OUTDIR)
written = []
rows.each do |row|
  item  = pageable.find { |i| i["id"] == row["id"] }
  label = labels[item["type"]] || "Publication"
  path  = File.join(OUTDIR, "#{row["slug"]}.md")
  body  = +"---\n"
  body << "layout: constellation\n"
  body << "title: #{"#{item["title"]} — Semuhi Sinanoglu".to_json}\n"
  body << "description: #{description(item, label).to_json}\n"
  body << "permalink: /work/#{row["slug"]}/\n"
  body << "pub_id: #{item["id"]}\n"
  body << "generated: #{MARKER}\n"
  body << "---\n"
  body << "{% include c-pub-page.html %}\n"
  File.write(path, body)
  written << File.basename(path)
end

# Drop stubs this script wrote earlier that no longer have an item.
Dir[File.join(OUTDIR, "*.md")].each do |f|
  next if written.include?(File.basename(f))
  next unless File.read(f).include?(MARKER)
  File.delete(f)
  puts "removed stale #{File.basename(f)}"
end

header = <<~HEAD
  # GENERATED by tools/gen-pub-pages.rb — do not edit by hand.
  # id -> slug for the publications that have their own page under /work/<slug>/.
  # Every list of publications on the site looks an item up here and links to
  # the local page when there is one: the wall (c-wall.html), the portfolio
  # rows (c-thread-row.html), the Latest strip (c-latest.html), the Spotlight
  # cards (c-flag-card.html), and the home map (network.js, via c-data.html).
  # No entry means the item links straight to the publisher.
HEAD
File.write(MAP, header + rows.map { |r| "- { id: #{r["id"]}, slug: #{r["slug"].to_json} }" }.join("\n") + "\n")

puts "#{rows.size} pages written to work/, #{items.size - rows.size} items stay wall-only (wrong type or no abstract)"
